
name = "DashMantineComponents"
uuid = "1b08a953-4be3-4667-9a23-1f1a4c7185d7"
authors = ["Snehil Vijay <snehilvj@outlook.com>"]
version = "0.2.1"

[deps]
Dash = "1b08a953-4be3-4667-9a23-3db579824955"

[compat]
julia = "1.2"
Dash = "0.1.3"
